version: '3.7'

services:
  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 2052:3000
      - 2053:3000
      - 3001:3000
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
