name: front CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy-front:
    name: deploy front
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SECOND_WORK_DIR }}
            docker compose down

            cd ${{ secrets.FIRST_WORK_DIR }}
            git reset HEAD --hard
            git checkout ${{ secrets.MAIN_BRANCH }}
            git pull

            cd ${{ secrets.SECOND_WORK_DIR }}
            docker compose up --build -d
      - name: cleanup
        run: rm -rf ~/.ssh
