name: front CI/CD

on:
  push:
    branches: [ main ]

jobs:

  build-front:
    name: build front image
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@v3

      - name: set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: set ip docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to docker hub registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./kadoo/dockerfile2
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/talebi-front:latest
