name: front CI/CD

on:
  push:
    branches: [ main ]

jobs:

  build-front:
    name: build front image
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@v3

      - name: set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: set ip docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to docker hub registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./kadoo/dockerfile2
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/talebi-front:latest


  deploy-front:
    name: deploy front
    runs-on: ubuntu-latest
    needs: build-front
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SECOND_WORK_DIR }}
            docker compose down
            docker image rm navid2001mousavi/talebi-front:latest
            docker image prune -f

            cd ${{ secrets.FIRST_WORK_DIR }}
            git reset HEAD --hard
            git checkout ${{ secrets.MAIN_BRANCH }}
            git pull

            cd ${{ secrets.SECOND_WORK_DIR }}
            docker compose -f docker-compose-server.yml up --build -d
      - name: cleanup
        run: rm -rf ~/.ssh
